version: "3"
services:
  original:
    build:
      context: .
      dockerfile: docker/original/Dockerfile
    tty: true
    stdin_open: true
  go-git:
    build:
      context: .
      dockerfile: docker/go-git/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/go/go-git/
      - /go/go-git/bin/
      - /go/go-git/.dircache